name: Astronomy Picture of the Day

on:
  workflow_dispatch

env:
  api_key: ${{ secrets.API_KEY }}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  download_reports:
    runs-on: ubuntu-latest
    name: downloading_reports

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - run: > 
        ARTIFACT_ID=$(curl -L -H "Accept: application/vnd.github+json" 
        -H "X-GitHub-Api-Version: 2022-11-28" 
        "https://api.github.com/repos/avgorjev/git_api_nasa/actions/artifacts?name=reports" 
        | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id'])") 
        && 
        curl -L
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.API_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        https://api.github.com/repos/avgorjev/git_api_nasa/actions/artifacts/$ARTIFACT_ID/zip 
        -o artifacts.zip
        &&
        REPORT_ID=$(curl -L -H "Accept: application/vnd.github+json" 
        -H "X-GitHub-Api-Version: 2022-11-28" 
        "https://api.github.com/repos/avgorjev/git_api_nasa/actions/artifacts?name=github-pages" 
        | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id'])") 
        && 
        curl -L
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.API_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        https://api.github.com/repos/avgorjev/git_api_nasa/actions/artifacts/$REPORT_ID/zip 
        -o pages.zip
    - run: mkdir reports 
        && unzip artifacts.zip -d reports
    - run: mkdir all_pages history_pages
        && unzip pages.zip -d all_pages
        && tar -xvf all_pages/artifact.tar -C history_pages
    - run: cp -r history_pages/history reports
    - name: Save results
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path:
          reports
        retention-days: 1
        

  api_tests:

    runs-on: ubuntu-latest
    needs: download_reports
    name: running_tests

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download artifact
      uses: actions/download-artifact@v3
    - name: All tests (with pytest and allure)
      run: |
        pytest -v -s --alluredir reports
      continue-on-error: true
    - name: Save results
      uses: actions/upload-artifact@v3
      with: 
        name: reports
        path:
          reports
        retention-days: 1

  prepare_reports:
    
    runs-on: macos-latest
    needs: api_tests
    name: creating_report
    
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: brew install allure
      - name: Download artifact
        uses: actions/download-artifact@v3
      - run: allure generate -c reports -o _site
      - name: Save reports
        uses: actions/upload-artifact@v3
        with: 
          name: _site
          path:
            _site
          retention-days: 1

  show_reports:
    
    runs-on: ubuntu-latest
    needs: prepare_reports
    name: screening_report
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
