name: Astronomy Picture of the Day

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Select a test'
        required: true
        default: 'all tests'
        type: choice
        options:
          - all_tests
          - first_test
          - second_test    

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api_tests:

    runs-on: ubuntu-latest
    name: running_tests

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: All tests (with pytest and allure)
      if: "github.event.inputs.deployment_target == 'all tests'"
      run: |
        pytest -v -s --alluredir reports
    - name: First test (with pytest and allure)
      if: "github.event.inputs.deployment_target == 'first test'"
      run: |
        pytest -v -s test_api_nasa.py::test_apod_today --alluredir reports
    - name: Second test (with pytest and allure)
      if: "github.event.inputs.deployment_target == 'second test'"
      run: |
        pytest -v -s test_api_nasa.py::test_apod_more_oldest --alluredir reports
    - name: Save results
      uses: actions/upload-artifact@v4
      with: 
        name: reports
        path:
          reports
        retention-days: 1

  prepare_reports:
    
    runs-on: macos-latest
    needs: api_tests
    name: creating_report
    
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: brew install allure
      - name: Download artifact
        uses: actions/download-artifact@v4
      - run: allure generate -c reports -o _site
      - name: Save reports
        uses: actions/upload-artifact@v4
        with: 
          name: _site
          path:
            _site
          retention-days: 1

  show_reports:
    
    runs-on: ubuntu-latest
    needs: prepare_reports
    name: screening_report
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
