name: Astronomy Picture of the Day

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  api_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -v -s --alluredir reports
    - name: Save results
      uses: actions/upload-artifact@v4
      with: 
        name: reports
        path:
          reports
        retention-days: 1

  prepare_reports:
    
    runs-on: macos-latest
    needs: api_tests
    name: Creating report
    
    steps:
      - uses: actions/setup-java@v3
        with:
          distibution: 'microsoft'
          java-version: '17'
      - run: brew install allure
      - name: Download artifact
        uses: actions/download-artifact@v3
      - run: allure generate -c reports -o _site
      - name: Save reports
        uses: actions/upload-artifact@v3
        with: 
          name: _site
          path:
            _site
          retention-days: 1
